-- =====================================================================
--  Moments - database schema
--  Postgres / Supabase. Run this whole file once in the SQL editor.
--
--  Design notes
--   * One shared copy: this database is the single source of truth.
--     Devices hold a cache + an outbox, never an independent copy.
--   * Every id is a UUID generated by whoever creates the row (usually
--     the client), so an offline device can create an event and replay
--     it later without ever producing a duplicate.
--   * Authorization lives here, in RLS + SECURITY DEFINER functions.
--     The UI hides things; the database is what actually enforces them.
--   * Events are soft-deleted and every change is appended to
--     event_edit_history, so nothing is ever destroyed by an edit.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- 1. People and families
-- ---------------------------------------------------------------------

create table if not exists public.users (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text,
  display_name  text not null default 'Family member',
  avatar_hue    int  not null default 210,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.families (
  id          uuid primary key default gen_random_uuid(),
  name        text not null default 'Our family',
  owner_id    uuid not null references public.users(id) on delete restrict,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

do $$ begin
  create type public.family_role as enum ('owner', 'member', 'viewer');
exception when duplicate_object then null; end $$;

create table if not exists public.family_members (
  id                 uuid primary key default gen_random_uuid(),
  family_id          uuid not null references public.families(id) on delete cascade,
  user_id            uuid not null references public.users(id) on delete cascade,
  role               public.family_role not null default 'member',
  can_view           boolean not null default true,
  can_add            boolean not null default true,
  can_edit           boolean not null default true,
  can_delete         boolean not null default false,
  can_view_stats     boolean not null default true,
  can_manage_members boolean not null default false,
  invited_by         uuid references public.users(id) on delete set null,
  joined_at          timestamptz not null default now(),
  unique (family_id, user_id)
);
create index if not exists family_members_user_idx on public.family_members(user_id);

create table if not exists public.family_invites (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references public.families(id) on delete cascade,
  code        text not null unique,
  role        public.family_role not null default 'member',
  label       text,
  created_by  uuid not null references public.users(id) on delete cascade,
  expires_at  timestamptz not null default (now() + interval '14 days'),
  accepted_by uuid references public.users(id) on delete set null,
  accepted_at timestamptz,
  revoked_at  timestamptz,
  created_at  timestamptz not null default now()
);

-- A child profile. One today; the schema already supports several.
create table if not exists public.profiles (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references public.families(id) on delete cascade,
  name        text not null,
  colour_hue  int not null default 210,
  birth_year  int,
  is_archived boolean not null default false,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists profiles_family_idx on public.profiles(family_id);

-- ---------------------------------------------------------------------
-- 2. Vocabulary: triggers and helpful actions (family-owned, editable)
-- ---------------------------------------------------------------------

create table if not exists public.triggers (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references public.families(id) on delete cascade,
  name        text not null,
  is_default  boolean not null default false,
  is_pinned   boolean not null default false,
  is_archived boolean not null default false,
  sort_order  int not null default 0,
  created_by  uuid references public.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (family_id, name)
);
create index if not exists triggers_family_idx on public.triggers(family_id);

create table if not exists public.helpful_actions (
  id          uuid primary key default gen_random_uuid(),
  family_id   uuid not null references public.families(id) on delete cascade,
  name        text not null,
  is_default  boolean not null default false,
  is_pinned   boolean not null default false,
  is_archived boolean not null default false,
  sort_order  int not null default 0,
  created_by  uuid references public.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (family_id, name)
);
create index if not exists helpful_actions_family_idx on public.helpful_actions(family_id);

-- ---------------------------------------------------------------------
-- 3. Events
-- ---------------------------------------------------------------------

create table if not exists public.events (
  id               uuid primary key,                -- generated by the client
  family_id        uuid not null references public.families(id) on delete cascade,
  profile_id       uuid not null references public.profiles(id) on delete cascade,
  created_by       uuid not null references public.users(id) on delete restrict,
  updated_by       uuid references public.users(id) on delete set null,
  start_time       timestamptz not null,
  end_time         timestamptz,
  duration_seconds int check (duration_seconds is null or duration_seconds >= 0),
  difficulty       int check (difficulty between 1 and 10),
  description      text,
  location         text,
  notes            text,
  sleep_quality    text check (sleep_quality in ('poor','okay','good')),
  hungry           text check (hungry in ('yes','no','unknown')),
  school_day       boolean,
  unusual_day      boolean,
  status           text not null default 'complete' check (status in ('draft','complete')),
  version          int  not null default 1,
  deleted_at       timestamptz,
  deleted_by       uuid references public.users(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint events_complete_needs_difficulty
    check (status = 'draft' or difficulty is not null)
);
create index if not exists events_family_start_idx on public.events(family_id, start_time desc);
create index if not exists events_profile_start_idx on public.events(profile_id, start_time desc);
create index if not exists events_updated_idx on public.events(family_id, updated_at desc);
alter table public.events replica identity full;

create table if not exists public.event_triggers (
  event_id   uuid not null references public.events(id) on delete cascade,
  trigger_id uuid not null references public.triggers(id) on delete cascade,
  primary key (event_id, trigger_id)
);
create index if not exists event_triggers_trigger_idx on public.event_triggers(trigger_id);

create table if not exists public.event_helpful_actions (
  event_id          uuid not null references public.events(id) on delete cascade,
  helpful_action_id uuid not null references public.helpful_actions(id) on delete cascade,
  primary key (event_id, helpful_action_id)
);
create index if not exists event_helpful_idx on public.event_helpful_actions(helpful_action_id);

-- Append-only. Edits never overwrite it.
create table if not exists public.event_edit_history (
  id          uuid primary key default gen_random_uuid(),
  event_id    uuid not null references public.events(id) on delete cascade,
  family_id   uuid not null references public.families(id) on delete cascade,
  changed_by  uuid references public.users(id) on delete set null,
  action      text not null check (action in ('created','updated','deleted','restored')),
  changes     jsonb not null default '[]'::jsonb,
  version     int,
  changed_at  timestamptz not null default now()
);
create index if not exists event_history_event_idx on public.event_edit_history(event_id, changed_at desc);

-- ---------------------------------------------------------------------
-- 4. Authorization helpers (SECURITY DEFINER: they must see past RLS)
-- ---------------------------------------------------------------------

create or replace function public.is_family_member(p_family uuid)
returns boolean language sql stable security definer set search_path = public as $fn$
  select exists (
    select 1 from public.family_members m
    where m.family_id = p_family and m.user_id = auth.uid()
  );
$fn$;

create or replace function public.has_perm(p_family uuid, p_perm text)
returns boolean language plpgsql stable security definer set search_path = public as $fn$
declare m public.family_members%rowtype;
begin
  select * into m from public.family_members
   where family_id = p_family and user_id = auth.uid();
  if not found then return false; end if;
  if m.role = 'owner' then return true; end if;   -- the owner always holds every permission
  return case p_perm
    when 'view'           then m.can_view
    when 'add'            then m.can_add
    when 'edit'           then m.can_edit
    when 'delete'         then m.can_delete
    when 'stats'          then m.can_view_stats
    when 'manage_members' then m.can_manage_members
    else false end;
end; $fn$;

create or replace function public.require_perm(p_family uuid, p_perm text)
returns void language plpgsql stable security definer set search_path = public as $fn$
begin
  if not public.has_perm(p_family, p_perm) then
    raise exception 'not_allowed: you do not have permission to % in this family', p_perm
      using errcode = '42501';
  end if;
end; $fn$;

-- ---------------------------------------------------------------------
-- 5. Row level security
-- ---------------------------------------------------------------------

alter table public.users                 enable row level security;
alter table public.families              enable row level security;
alter table public.family_members        enable row level security;
alter table public.family_invites        enable row level security;
alter table public.profiles              enable row level security;
alter table public.triggers              enable row level security;
alter table public.helpful_actions       enable row level security;
alter table public.events                enable row level security;
alter table public.event_triggers        enable row level security;
alter table public.event_helpful_actions enable row level security;
alter table public.event_edit_history    enable row level security;

drop policy if exists users_self_read on public.users;
create policy users_self_read on public.users for select to authenticated
  using (
    id = auth.uid()
    or exists (                      -- family members can see each other's names
      select 1 from public.family_members me
      join public.family_members them on them.family_id = me.family_id
      where me.user_id = auth.uid() and them.user_id = public.users.id
    )
  );
drop policy if exists users_self_insert on public.users;
create policy users_self_insert on public.users for insert to authenticated
  with check (id = auth.uid());
drop policy if exists users_self_write on public.users;
create policy users_self_write on public.users for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists families_read on public.families;
create policy families_read on public.families for select to authenticated
  using (public.is_family_member(id));
drop policy if exists families_update on public.families;
create policy families_update on public.families for update to authenticated
  using (public.has_perm(id, 'manage_members'))
  with check (public.has_perm(id, 'manage_members'));

drop policy if exists members_read on public.family_members;
create policy members_read on public.family_members for select to authenticated
  using (public.is_family_member(family_id));
drop policy if exists members_manage on public.family_members;
create policy members_manage on public.family_members for update to authenticated
  using (public.has_perm(family_id, 'manage_members'))
  with check (public.has_perm(family_id, 'manage_members'));
drop policy if exists members_remove on public.family_members;
create policy members_remove on public.family_members for delete to authenticated
  using (
    (public.has_perm(family_id, 'manage_members') and role <> 'owner')
    or user_id = auth.uid()                       -- anyone may leave a family
  );

drop policy if exists invites_read on public.family_invites;
create policy invites_read on public.family_invites for select to authenticated
  using (public.has_perm(family_id, 'manage_members'));
drop policy if exists invites_write on public.family_invites;
create policy invites_write on public.family_invites for insert to authenticated
  with check (public.has_perm(family_id, 'manage_members') and created_by = auth.uid());
drop policy if exists invites_revoke on public.family_invites;
create policy invites_revoke on public.family_invites for update to authenticated
  using (public.has_perm(family_id, 'manage_members'))
  with check (public.has_perm(family_id, 'manage_members'));

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
  using (public.has_perm(family_id, 'view'));
drop policy if exists profiles_write on public.profiles;
create policy profiles_write on public.profiles for all to authenticated
  using (public.has_perm(family_id, 'manage_members'))
  with check (public.has_perm(family_id, 'manage_members'));

drop policy if exists triggers_read on public.triggers;
create policy triggers_read on public.triggers for select to authenticated
  using (public.has_perm(family_id, 'view'));
drop policy if exists triggers_insert on public.triggers;
create policy triggers_insert on public.triggers for insert to authenticated
  with check (public.has_perm(family_id, 'add'));
drop policy if exists triggers_update on public.triggers;
create policy triggers_update on public.triggers for update to authenticated
  using (public.has_perm(family_id, 'edit'))
  with check (public.has_perm(family_id, 'edit'));

drop policy if exists helpful_read on public.helpful_actions;
create policy helpful_read on public.helpful_actions for select to authenticated
  using (public.has_perm(family_id, 'view'));
drop policy if exists helpful_insert on public.helpful_actions;
create policy helpful_insert on public.helpful_actions for insert to authenticated
  with check (public.has_perm(family_id, 'add'));
drop policy if exists helpful_update on public.helpful_actions;
create policy helpful_update on public.helpful_actions for update to authenticated
  using (public.has_perm(family_id, 'edit'))
  with check (public.has_perm(family_id, 'edit'));

-- Events are written through save_event() / delete_event(), never directly.
drop policy if exists events_read on public.events;
create policy events_read on public.events for select to authenticated
  using (public.has_perm(family_id, 'view'));

drop policy if exists event_triggers_read on public.event_triggers;
create policy event_triggers_read on public.event_triggers for select to authenticated
  using (exists (select 1 from public.events e
                 where e.id = event_id and public.has_perm(e.family_id, 'view')));

drop policy if exists event_helpful_read on public.event_helpful_actions;
create policy event_helpful_read on public.event_helpful_actions for select to authenticated
  using (exists (select 1 from public.events e
                 where e.id = event_id and public.has_perm(e.family_id, 'view')));

drop policy if exists history_read on public.event_edit_history;
create policy history_read on public.event_edit_history for select to authenticated
  using (public.has_perm(family_id, 'view'));

-- ---------------------------------------------------------------------
-- 6. The event view the app reads (event + its trigger / helpful ids)
-- ---------------------------------------------------------------------

create or replace view public.event_view
with (security_invoker = true) as
select
  e.*,
  coalesce((select array_agg(t.trigger_id) from public.event_triggers t
             where t.event_id = e.id), '{}')::uuid[] as trigger_ids,
  coalesce((select array_agg(h.helpful_action_id) from public.event_helpful_actions h
             where h.event_id = e.id), '{}')::uuid[] as helpful_ids
from public.events e;

-- ---------------------------------------------------------------------
-- 7. Account bootstrap
-- ---------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $fn$
begin
  insert into public.users (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'), ''),
             split_part(coalesce(new.email, 'Family member'), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end; $fn$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- 8. Family creation + invitations
-- ---------------------------------------------------------------------

create or replace function public.create_family(p_family_name text, p_child_name text)
returns jsonb language plpgsql security definer set search_path = public as $fn$
declare
  v_uid    uuid := auth.uid();
  v_family uuid;
  v_profile uuid;
  v_name   text;
  v_order  int := 0;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode = '42501'; end if;

  insert into public.users (id, display_name)
  values (v_uid, 'Family member') on conflict (id) do nothing;

  insert into public.families (name, owner_id)
  values (coalesce(nullif(trim(p_family_name), ''), 'Our family'), v_uid)
  returning id into v_family;

  insert into public.family_members
    (family_id, user_id, role, can_view, can_add, can_edit, can_delete, can_view_stats, can_manage_members)
  values (v_family, v_uid, 'owner', true, true, true, true, true, true);

  insert into public.profiles (family_id, name)
  values (v_family, coalesce(nullif(trim(p_child_name), ''), 'My child'))
  returning id into v_profile;

  foreach v_name in array array[
    'Homework','School','Hunger','Tired','Noise','Change of plans','Screen time ending',
    'Argument','Frustration','Waiting','Social situation','Overwhelmed','Unknown','Other'
  ] loop
    insert into public.triggers (family_id, name, is_default, sort_order, created_by)
    values (v_family, v_name, true, v_order, v_uid)
    on conflict (family_id, name) do nothing;
    v_order := v_order + 1;
  end loop;

  v_order := 0;
  foreach v_name in array array[
    'Quiet room','Break','Talking','Food','Music','Going outside','Changing activity',
    'Hug','Time alone','Deep breaths','Water','Other'
  ] loop
    insert into public.helpful_actions (family_id, name, is_default, sort_order, created_by)
    values (v_family, v_name, true, v_order, v_uid)
    on conflict (family_id, name) do nothing;
    v_order := v_order + 1;
  end loop;

  return jsonb_build_object('family_id', v_family, 'profile_id', v_profile);
end; $fn$;

-- search_path includes `extensions` because Supabase installs pgcrypto there.
create or replace function public.create_invite(p_family uuid, p_role text, p_label text)
returns jsonb language plpgsql security definer set search_path = public, extensions as $fn$
declare v_code text;
begin
  perform public.require_perm(p_family, 'manage_members');
  v_code := upper(encode(gen_random_bytes(5), 'hex'));   -- 10 characters
  insert into public.family_invites (family_id, code, role, label, created_by)
  values (p_family, v_code, coalesce(p_role, 'member')::public.family_role,
          nullif(trim(p_label), ''), auth.uid());
  return jsonb_build_object('code', v_code);
end; $fn$;

create or replace function public.accept_invite(p_code text)
returns jsonb language plpgsql security definer set search_path = public as $fn$
declare
  v_uid uuid := auth.uid();
  v_inv public.family_invites%rowtype;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode = '42501'; end if;

  select * into v_inv from public.family_invites
   where code = upper(trim(p_code)) for update;

  if not found then raise exception 'invite_not_found' using errcode = 'P0002'; end if;
  if v_inv.revoked_at is not null then raise exception 'invite_revoked' using errcode = 'P0002'; end if;
  if v_inv.accepted_at is not null then raise exception 'invite_already_used' using errcode = 'P0002'; end if;
  if v_inv.expires_at < now() then raise exception 'invite_expired' using errcode = 'P0002'; end if;

  insert into public.users (id, display_name) values (v_uid, 'Family member')
  on conflict (id) do nothing;

  insert into public.family_members
    (family_id, user_id, role, can_view, can_add, can_edit, can_delete, can_view_stats,
     can_manage_members, invited_by)
  values (
    v_inv.family_id, v_uid, v_inv.role,
    true,
    v_inv.role <> 'viewer',
    v_inv.role <> 'viewer',
    false,
    true,
    false,
    v_inv.created_by
  )
  on conflict (family_id, user_id) do nothing;

  update public.family_invites
     set accepted_by = v_uid, accepted_at = now()
   where id = v_inv.id;

  return jsonb_build_object('family_id', v_inv.family_id);
end; $fn$;

-- ---------------------------------------------------------------------
-- 9. save_event - the one write path for events
--
--    * Insert and update share a path, keyed on the client-generated id,
--      so replaying a queued offline write can never create a duplicate.
--    * p_expected_version null  => "I believe this is new".
--      If the row already exists it is treated as a replay and the
--      current server row is returned unchanged.
--    * p_expected_version set   => optimistic concurrency. A mismatch
--      returns status 'conflict' with the server's row; nothing is lost
--      and the app asks the person what to keep.
-- ---------------------------------------------------------------------

create or replace function public.save_event(p jsonb, p_expected_version int default null)
returns jsonb language plpgsql security definer set search_path = public as $fn$
declare
  v_uid       uuid := auth.uid();
  v_id        uuid := (p->>'id')::uuid;
  v_family    uuid := (p->>'family_id')::uuid;
  v_existing  public.events%rowtype;
  v_new       public.events%rowtype;
  v_changes   jsonb := '[]'::jsonb;
  v_action    text  := 'updated';
  v_trigs     uuid[] := coalesce((select array_agg(value::uuid)
                                    from jsonb_array_elements_text(coalesce(p->'trigger_ids','[]'::jsonb))), '{}');
  v_helps     uuid[] := coalesce((select array_agg(value::uuid)
                                    from jsonb_array_elements_text(coalesce(p->'helpful_ids','[]'::jsonb))), '{}');
  v_old_trigs uuid[];
  v_old_helps uuid[];
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode = '42501'; end if;
  if v_id is null or v_family is null then raise exception 'id_and_family_required'; end if;
  perform public.require_perm(v_family, 'view');

  -- Everything this event points at must belong to the same family. The UI
  -- only offers valid options; this is the check that actually holds.
  if (p ? 'profile_id') and not exists (
    select 1 from public.profiles pr
    where pr.id = (p->>'profile_id')::uuid and pr.family_id = v_family
  ) then
    raise exception 'profile_not_in_family' using errcode = '42501';
  end if;

  if exists (
    select 1 from unnest(v_trigs) as x(id)
    where not exists (select 1 from public.triggers t where t.id = x.id and t.family_id = v_family)
  ) then
    raise exception 'trigger_not_in_family' using errcode = '42501';
  end if;

  if exists (
    select 1 from unnest(v_helps) as x(id)
    where not exists (select 1 from public.helpful_actions h where h.id = x.id and h.family_id = v_family)
  ) then
    raise exception 'helpful_action_not_in_family' using errcode = '42501';
  end if;

  select * into v_existing from public.events where id = v_id for update;

  -- ---- insert -------------------------------------------------------
  if not found then
    perform public.require_perm(v_family, 'add');

    insert into public.events (
      id, family_id, profile_id, created_by, updated_by, start_time, end_time,
      duration_seconds, difficulty, description, location, notes,
      sleep_quality, hungry, school_day, unusual_day, status, version,
      created_at, updated_at
    ) values (
      v_id, v_family, (p->>'profile_id')::uuid, v_uid, v_uid,
      (p->>'start_time')::timestamptz,
      nullif(p->>'end_time','')::timestamptz,
      nullif(p->>'duration_seconds','')::int,
      nullif(p->>'difficulty','')::int,
      nullif(p->>'description',''),
      nullif(p->>'location',''),
      nullif(p->>'notes',''),
      nullif(p->>'sleep_quality',''),
      nullif(p->>'hungry',''),
      nullif(p->>'school_day','')::boolean,
      nullif(p->>'unusual_day','')::boolean,
      coalesce(nullif(p->>'status',''), 'complete'),
      1,
      coalesce(nullif(p->>'created_at','')::timestamptz, now()),
      now()
    )
    returning * into v_new;

    v_action  := 'created';
    v_changes := jsonb_build_array(jsonb_build_object('field','event','to','created'));

  -- ---- replayed insert (already stored) ------------------------------
  elsif p_expected_version is null then
    return jsonb_build_object('status','ok','replay',true,
                              'event', public.event_json(v_id));

  -- ---- update ---------------------------------------------------------
  else
    perform public.require_perm(v_family, 'edit');

    -- Someone else got there first. Both sides are kept: the caller receives
    -- the server's row and decides what to do with its own copy.
    if v_existing.version <> p_expected_version then
      return jsonb_build_object('status','conflict',
                                'event', public.event_json(v_id));
    end if;

    select coalesce(array_agg(trigger_id order by trigger_id), '{}') into v_old_trigs
      from public.event_triggers where event_id = v_id;
    select coalesce(array_agg(helpful_action_id order by helpful_action_id), '{}') into v_old_helps
      from public.event_helpful_actions where event_id = v_id;

    update public.events set
      profile_id       = coalesce((p->>'profile_id')::uuid, profile_id),
      start_time       = coalesce((p->>'start_time')::timestamptz, start_time),
      end_time         = nullif(p->>'end_time','')::timestamptz,
      duration_seconds = nullif(p->>'duration_seconds','')::int,
      difficulty       = nullif(p->>'difficulty','')::int,
      description      = nullif(p->>'description',''),
      location         = nullif(p->>'location',''),
      notes            = nullif(p->>'notes',''),
      sleep_quality    = nullif(p->>'sleep_quality',''),
      hungry           = nullif(p->>'hungry',''),
      school_day       = nullif(p->>'school_day','')::boolean,
      unusual_day      = nullif(p->>'unusual_day','')::boolean,
      status           = coalesce(nullif(p->>'status',''), status),
      version          = version + 1,
      updated_by       = v_uid,
      updated_at       = now(),
      deleted_at       = null,
      deleted_by       = null
    where id = v_id
    returning * into v_new;

    v_changes := public.diff_events(v_existing, v_new);
    if v_existing.deleted_at is not null then v_action := 'restored'; end if;
  end if;

  -- ---- join tables ------------------------------------------------------
  delete from public.event_triggers
   where event_id = v_id and not (trigger_id = any(v_trigs));
  insert into public.event_triggers (event_id, trigger_id)
    select v_id, x.id from unnest(v_trigs) as x(id) on conflict do nothing;

  delete from public.event_helpful_actions
   where event_id = v_id and not (helpful_action_id = any(v_helps));
  insert into public.event_helpful_actions (event_id, helpful_action_id)
    select v_id, x.id from unnest(v_helps) as x(id) on conflict do nothing;

  if v_action = 'updated' then
    if coalesce(v_old_trigs,'{}') is distinct from
       coalesce((select array_agg(x.id order by x.id) from unnest(v_trigs) as x(id)), '{}') then
      v_changes := v_changes || jsonb_build_array(jsonb_build_object('field','triggers','to','changed'));
    end if;
    if coalesce(v_old_helps,'{}') is distinct from
       coalesce((select array_agg(x.id order by x.id) from unnest(v_helps) as x(id)), '{}') then
      v_changes := v_changes || jsonb_build_array(jsonb_build_object('field','what_helped','to','changed'));
    end if;
  end if;

  if v_action <> 'updated' or jsonb_array_length(v_changes) > 0 then
    insert into public.event_edit_history (event_id, family_id, changed_by, action, changes, version)
    values (v_id, v_family, v_uid, v_action, v_changes, v_new.version);
  end if;

  return jsonb_build_object('status','ok','event', public.event_json(v_id));
end; $fn$;

-- Field-by-field diff, used to build the human-readable edit history.
create or replace function public.diff_events(a public.events, b public.events)
returns jsonb language plpgsql immutable as $fn$
declare v jsonb := '[]'::jsonb;
begin
  if a.difficulty is distinct from b.difficulty then
    v := v || jsonb_build_array(jsonb_build_object('field','difficulty','from',a.difficulty,'to',b.difficulty));
  end if;
  if a.start_time is distinct from b.start_time then
    v := v || jsonb_build_array(jsonb_build_object('field','start_time','from',a.start_time,'to',b.start_time));
  end if;
  if a.duration_seconds is distinct from b.duration_seconds then
    v := v || jsonb_build_array(jsonb_build_object('field','duration','from',a.duration_seconds,'to',b.duration_seconds));
  end if;
  if a.description is distinct from b.description then
    v := v || jsonb_build_array(jsonb_build_object('field','description','from',a.description,'to',b.description));
  end if;
  if a.location is distinct from b.location then
    v := v || jsonb_build_array(jsonb_build_object('field','location','from',a.location,'to',b.location));
  end if;
  if a.notes is distinct from b.notes then
    v := v || jsonb_build_array(jsonb_build_object('field','notes','from',a.notes,'to',b.notes));
  end if;
  if a.sleep_quality is distinct from b.sleep_quality then
    v := v || jsonb_build_array(jsonb_build_object('field','sleep_quality','from',a.sleep_quality,'to',b.sleep_quality));
  end if;
  if a.hungry is distinct from b.hungry then
    v := v || jsonb_build_array(jsonb_build_object('field','hungry','from',a.hungry,'to',b.hungry));
  end if;
  if a.school_day is distinct from b.school_day then
    v := v || jsonb_build_array(jsonb_build_object('field','school_day','from',a.school_day,'to',b.school_day));
  end if;
  if a.unusual_day is distinct from b.unusual_day then
    v := v || jsonb_build_array(jsonb_build_object('field','unusual_day','from',a.unusual_day,'to',b.unusual_day));
  end if;
  if a.status is distinct from b.status then
    v := v || jsonb_build_array(jsonb_build_object('field','status','from',a.status,'to',b.status));
  end if;
  return v;
end; $fn$;

create or replace function public.event_json(p_id uuid)
returns jsonb language sql stable security definer set search_path = public as $fn$
  select to_jsonb(v) from public.event_view v where v.id = p_id;
$fn$;

create or replace function public.delete_event(p_id uuid, p_expected_version int default null)
returns jsonb language plpgsql security definer set search_path = public as $fn$
declare
  v_uid uuid := auth.uid();
  v_ev  public.events%rowtype;
begin
  select * into v_ev from public.events where id = p_id for update;
  if not found then
    return jsonb_build_object('status','ok','already_gone',true);   -- replay-safe
  end if;

  perform public.require_perm(v_ev.family_id, 'delete');

  if v_ev.deleted_at is not null then
    return jsonb_build_object('status','ok','event', public.event_json(p_id));
  end if;
  if p_expected_version is not null and v_ev.version <> p_expected_version then
    return jsonb_build_object('status','conflict','event', public.event_json(p_id));
  end if;

  update public.events
     set deleted_at = now(), deleted_by = v_uid, updated_by = v_uid,
         updated_at = now(), version = version + 1
   where id = p_id;

  insert into public.event_edit_history (event_id, family_id, changed_by, action, changes, version)
  values (p_id, v_ev.family_id, v_uid, 'deleted',
          jsonb_build_array(jsonb_build_object('field','event','to','deleted')), v_ev.version + 1);

  return jsonb_build_object('status','ok','event', public.event_json(p_id));
end; $fn$;

create or replace function public.restore_event(p_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $fn$
declare
  v_uid uuid := auth.uid();
  v_ev  public.events%rowtype;
begin
  select * into v_ev from public.events where id = p_id for update;
  if not found then raise exception 'event_not_found' using errcode = 'P0002'; end if;
  perform public.require_perm(v_ev.family_id, 'edit');

  update public.events
     set deleted_at = null, deleted_by = null, updated_by = v_uid,
         updated_at = now(), version = version + 1
   where id = p_id;

  insert into public.event_edit_history (event_id, family_id, changed_by, action, changes, version)
  values (p_id, v_ev.family_id, v_uid, 'restored',
          jsonb_build_array(jsonb_build_object('field','event','to','restored')), v_ev.version + 1);

  return jsonb_build_object('status','ok','event', public.event_json(p_id));
end; $fn$;

-- ---------------------------------------------------------------------
-- 10. Export and erase
-- ---------------------------------------------------------------------

create or replace function public.export_family_data(p_family uuid)
returns jsonb language plpgsql security definer set search_path = public as $fn$
begin
  perform public.require_perm(p_family, 'view');
  return jsonb_build_object(
    'exported_at', now(),
    'family',   (select to_jsonb(f) from public.families f where f.id = p_family),
    'members',  (select coalesce(jsonb_agg(to_jsonb(m)), '[]'::jsonb)
                   from public.family_members m where m.family_id = p_family),
    'people',   (select coalesce(jsonb_agg(jsonb_build_object('id',u.id,'display_name',u.display_name)), '[]'::jsonb)
                   from public.users u
                   join public.family_members m on m.user_id = u.id
                  where m.family_id = p_family),
    'profiles', (select coalesce(jsonb_agg(to_jsonb(pr)), '[]'::jsonb)
                   from public.profiles pr where pr.family_id = p_family),
    'triggers', (select coalesce(jsonb_agg(to_jsonb(t)), '[]'::jsonb)
                   from public.triggers t where t.family_id = p_family),
    'helpful_actions', (select coalesce(jsonb_agg(to_jsonb(h)), '[]'::jsonb)
                   from public.helpful_actions h where h.family_id = p_family),
    'events',   (select coalesce(jsonb_agg(to_jsonb(v)), '[]'::jsonb)
                   from public.event_view v where v.family_id = p_family),
    'event_edit_history', (select coalesce(jsonb_agg(to_jsonb(eh)), '[]'::jsonb)
                   from public.event_edit_history eh where eh.family_id = p_family)
  );
end; $fn$;

-- Leaves the family. If the caller is the owner, the whole family and
-- everything in it is deleted - that is the family's data, not just theirs.
create or replace function public.delete_my_data(p_family uuid, p_delete_family boolean default false)
returns jsonb language plpgsql security definer set search_path = public as $fn$
declare
  v_uid uuid := auth.uid();
  v_owner uuid;
begin
  select owner_id into v_owner from public.families where id = p_family;
  if v_owner is null then raise exception 'family_not_found' using errcode = 'P0002'; end if;

  if v_owner = v_uid then
    if not p_delete_family then
      raise exception 'owner_must_confirm_family_deletion' using errcode = 'P0001';
    end if;
    delete from public.families where id = p_family;     -- cascades everywhere
    return jsonb_build_object('status','family_deleted');
  end if;

  delete from public.family_members where family_id = p_family and user_id = v_uid;
  return jsonb_build_object('status','left_family');
end; $fn$;

-- ---------------------------------------------------------------------
-- 11. Realtime
-- ---------------------------------------------------------------------

do $$
declare t text;
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
  foreach t in array array['events','triggers','helpful_actions','family_members','profiles'] loop
    begin
      execute format('alter publication supabase_realtime add table public.%I', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ---------------------------------------------------------------------
-- 12. Grants (RLS still decides; these just open the door)
-- ---------------------------------------------------------------------

grant usage on schema public to authenticated;
grant select on public.users, public.families, public.family_members, public.family_invites,
                public.profiles, public.triggers, public.helpful_actions, public.events,
                public.event_triggers, public.event_helpful_actions,
                public.event_edit_history, public.event_view to authenticated;
grant insert, update on public.users, public.triggers, public.helpful_actions to authenticated;
grant insert, update on public.family_invites to authenticated;
grant update, delete on public.family_members to authenticated;
grant update on public.families to authenticated;
grant insert, update, delete on public.profiles to authenticated;

revoke all on function public.save_event(jsonb, int) from public;
grant execute on function
  public.save_event(jsonb, int),
  public.delete_event(uuid, int),
  public.restore_event(uuid),
  public.create_family(text, text),
  public.create_invite(uuid, text, text),
  public.accept_invite(text),
  public.export_family_data(uuid),
  public.delete_my_data(uuid, boolean),
  public.has_perm(uuid, text),
  public.is_family_member(uuid)
to authenticated;
